In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
training_data = pd.read_csv(r"C:\Users\obsession\Desktop\Projeto DAA\Dataset\training_data.csv", encoding='latin-1')
test_data = pd.read_csv(r"C:\Users\obsession\Desktop\Projeto DAA\Dataset\test_data.csv", encoding='latin-1')

In [3]:
'''
Preparar o dataset
'''
#City name é sempre porto logo pode-se fazer drop
#Drop
training_data = training_data.drop(['city_name'], axis=1)
#Average percipitation é sempre 0 logo pode-se fazer drop
training_data = training_data.drop(['AVERAGE_PRECIPITATION'], axis=1)

#Precisamos de escalar certos valores para 0-1
from sklearn.preprocessing import MinMaxScaler

training_data['AVERAGE_FREE_FLOW_SPEED'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_FREE_FLOW_SPEED']).reshape(-1,1))
training_data['AVERAGE_TIME_DIFF'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_TIME_DIFF']).reshape(-1,1))
training_data['AVERAGE_FREE_FLOW_TIME'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_FREE_FLOW_TIME']).reshape(-1,1))
training_data['AVERAGE_TEMPERATURE'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_TEMPERATURE']).reshape(-1,1))
training_data['AVERAGE_ATMOSP_PRESSURE'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_ATMOSP_PRESSURE']).reshape(-1,1))
training_data['AVERAGE_HUMIDITY'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_HUMIDITY']).reshape(-1,1))
training_data['AVERAGE_WIND_SPEED'] = MinMaxScaler().fit_transform(np.array(training_data['AVERAGE_WIND_SPEED']).reshape(-1,1))

#Ordenar a dataframe por as datas
#training_data = training_data.sort_values(by='record_date')


In [4]:
#Usar as horas

dfdate= pd.to_datetime(training_data['record_date'])
#training_data['record_date'] =  pd.to_datetime(training_data['record_date'], infer_datetime_format=True)
# define the bins
bins = [0, 7, 11, 14, 17, 19, 21, 24]

# add custom labels if desired
labels = ['00:00-06:59', '07:00-10:59', '11:00-13:59', '14:00-16:59', '17:00-18:59', '19:00-20:59', '21:00-23:59']

# add the bins to the dataframe
training_data['Time Bin'] = pd.cut(dfdate.dt.hour, bins, labels=labels, right=False)
dfdate = pd.to_datetime(test_data['record_date'])
test_data['Time Bin'] = pd.cut(dfdate.dt.hour, bins, labels=labels, right=False)

def ismeia(cols):
    TimeBin=cols
    if TimeBin==labels[0]:
        return 1
    else:
        return 0
    
def issete(cols):
    TimeBin=cols
    if TimeBin==labels[1]:
        return 1
    else:
        return 0

def isonze(cols):
    TimeBin=cols
    if TimeBin==labels[2]:
        return 1
    else:
        return 0
    
def isquatorze(cols):
    TimeBin=cols
    if TimeBin==labels[3]:
        return 1
    else:
        return 0
    
def isdessasete(cols):
    TimeBin=cols
    if TimeBin==labels[4]:
        return 1
    else:
        return 0
    

def isdezanove(cols):
    TimeBin=cols
    if TimeBin==labels[5]:
        return 1
    else:
        return 0
    
def isvinteum(cols):
    TimeBin=cols
    if TimeBin==labels[6]:
        return 1
    else:
        return 0
    


training_data[labels[0]] = training_data['Time Bin'].apply(ismeia)
training_data[labels[1]] = training_data['Time Bin'].apply(issete)
training_data[labels[2]] = training_data['Time Bin'].apply(isonze)
training_data[labels[3]] = training_data['Time Bin'].apply(isquatorze)
training_data[labels[4]] = training_data['Time Bin'].apply(isdessasete)
training_data[labels[5]] = training_data['Time Bin'].apply(isdezanove)
training_data[labels[6]] = training_data['Time Bin'].apply(isvinteum)

training_data=training_data.drop('Time Bin',axis=1)

test_data[labels[0]] = test_data['Time Bin'].apply(ismeia)
test_data[labels[1]] = test_data['Time Bin'].apply(issete)
test_data[labels[2]] = test_data['Time Bin'].apply(isonze)
test_data[labels[3]] = test_data['Time Bin'].apply(isquatorze)
test_data[labels[4]] = test_data['Time Bin'].apply(isdessasete)
test_data[labels[5]] = test_data['Time Bin'].apply(isdezanove)
test_data[labels[6]] = test_data['Time Bin'].apply(isvinteum)


test_data=test_data.drop('Time Bin',axis=1)

training_data

record_date AVERAGE_SPEED_DIFF  AVERAGE_FREE_FLOW_SPEED  \
0     2019-08-29 07:00:00             Medium                 0.433071   
1     2018-08-10 14:00:00               High                 0.440945   
2     2019-09-01 16:00:00               High                 0.318898   
3     2019-02-26 11:00:00               High                 0.271654   
4     2019-06-06 12:00:00             Medium                 0.437008   
...                   ...                ...                      ...   
6807  2019-02-23 09:00:00                Low                 0.421260   
6808  2019-06-08 18:00:00             Medium                 0.330709   
6809  2018-10-02 04:00:00               None                 0.358268   
6810  2019-01-30 01:00:00               None                 0.437008   
6811  2019-06-15 21:00:00             Medium                 0.440945   

      AVERAGE_TIME_DIFF  AVERAGE_FREE_FLOW_TIME LUMINOSITY  \
0              0.038786                0.381098      LIGHT   
1              0.162901                0.625000      LIGHT   
2              0.129511                0.591463      LIGHT   
3              0.205734                0.727134      LIGHT   
4              0.169983                0.466463      LIGHT   
...                 ...                     ...        ...   
6807           0.012479                0.617378      LIGHT   
6808           0.175042                0.464939      LIGHT   
6809           0.000000                0.650915       DARK   
6810           0.000000                0.596037       DARK   
6811           0.110961                0.483232       DARK   

      AVERAGE_TEMPERATURE  AVERAGE_ATMOSP_PRESSURE  AVERAGE_HUMIDITY  \
0                0.428571                 0.708333          1.000000   
1                0.600000                 0.750000          0.453488   
2                0.742857                 0.604167          0.546512   
3                0.514286                 0.833333          0.395349   
4                0.428571                 0.479167          0.790698   
...                   ...                      ...               ...   
6807             0.257143                 0.937500          0.662791   
6808             0.485714                 0.729167          0.569767   
6809             0.428571                 0.729167          0.290698   
6810             0.228571                 0.687500          0.779070   
6811             0.428571                 0.750000          0.674419   

      AVERAGE_WIND_SPEED AVERAGE_CLOUDINESS AVERAGE_RAIN  00:00-06:59  \
0               0.214286                NaN          NaN            0   
1               0.357143          céu claro          NaN            0   
2               0.285714                NaN          NaN            0   
3               0.285714          céu claro          NaN            0   
4               0.714286                NaN          NaN            0   
...                  ...                ...          ...          ...   
6807            0.285714          céu claro          NaN            0   
6808            0.428571                NaN          NaN            0   
6809            0.285714          céu claro          NaN            1   
6810            0.071429     algumas nuvens          NaN            1   
6811            0.285714                NaN          NaN            0   

      07:00-10:59  11:00-13:59  14:00-16:59  17:00-18:59  19:00-20:59  \
0               1            0            0            0            0   
1               0            0            1            0            0   
2               0            0            1            0            0   
3               0            1            0            0            0   
4               0            1            0            0            0   
...           ...          ...          ...          ...          ...   
6807            1            0            0            0            0   
6808            0            0            0            1          

In [5]:
#Usar os dias
def isweekday(cols):
    dayofweek=cols
    if dayofweek=='Saturday' or dayofweek=='Sunday':
        return 0
    else:
        return 1

dfdate= pd.to_datetime(training_data['record_date'])

asd= dfdate.dt.day_name()
training_data['IsDayOfWeek'] = asd.apply(isweekday)


#Test Data

def isweekday(cols):
    dayofweek=cols
    if dayofweek=='Saturday' or dayofweek=='Sunday':
        return 0
    else:
        return 1

dfdate= pd.to_datetime(test_data['record_date'])

asd= dfdate.dt.day_name()
test_data['IsDayOfWeek'] = asd.apply(isweekday)

In [6]:
#cloudness
#nan

# céu claro
#ceu limpo

#nuvens dispersas
#algumas nuvens
#ceu pouco nublado
#nuvens quebrados
#nuvens qubradas

#nublado
#tempo nublado


training_data.replace(to_replace ="céu claro", 
                 value = 0.999999, 
                  inplace = True)

training_data.replace(to_replace ="céu limpo", 
                 value = 0.999999, 
                  inplace = True)

training_data.replace(to_replace ="nuvens dispersas", 
                 value = 0.666666, 
                  inplace = True)


training_data.replace(to_replace ="algumas nuvens", 
                 value = 0.666666, 
                  inplace = True)

training_data.replace(to_replace ="céu pouco nublado", 
                 value = 0.666666, 
                  inplace = True)

training_data.replace(to_replace ="nuvens quebrados", 
                 value = 0.666666, 
                  inplace = True)

training_data.replace(to_replace ="nuvens quebradas", 
                 value = 0.666666, 
                  inplace = True)

training_data.replace(to_replace ="nublado", 
                 value = 0.333333, 
                  inplace = True)

training_data.replace(to_replace ="tempo nublado", 
                 value = 0.333333, 
                  inplace = True)

training_data.replace(to_replace ="NULL", 
                 value = 0.3, 
                  inplace = True)


training_data.replace(to_replace =r'^\s*$', 
                 value = 0.3, 
                regex=True,
                 inplace = True)

training_data["AVERAGE_CLOUDINESS"] = training_data["AVERAGE_CLOUDINESS"].fillna("MISSING VALUE")

dftmp = training_data[training_data["AVERAGE_CLOUDINESS"]!="MISSING VALUE"]

mediaRAS = dftmp.mean()

training_data.replace(to_replace ="MISSING VALUE", 
                 value = mediaRAS, 
                  inplace = True)


In [7]:
#Agora temos de tratar da Luminosity

training_data.replace(to_replace ="DARK", 
                 value = 0.333333, 
                  inplace = True)

training_data.replace(to_replace ="LOW_LIGHT", 
                 value = 0.666666, 
                  inplace = True)

training_data.replace(to_replace ="LIGHT", 
                 value = 0.999999, 
                  inplace = True)


#Agora vamos dropar record date e rain
training_data = training_data.drop(['record_date'], axis=1)
training_data = training_data.drop(['AVERAGE_RAIN'], axis=1)

In [8]:
training_data.replace(to_replace ="None", 
                 value = 0, 
                  inplace = True)

training_data.replace(to_replace ="Low", 
                 value = 1, 
                  inplace = True)

training_data.replace(to_replace ="Medium", 
                 value = 2, 
                  inplace = True)

training_data.replace(to_replace ="High", 
                 value = 3, 
                  inplace = True)

training_data.replace(to_replace ="Very_High", 
                 value = 4, 
                  inplace = True)


In [9]:
##Split dataset
from sklearn.model_selection import train_test_split

X = training_data.drop('AVERAGE_SPEED_DIFF', axis=1)
y = training_data['AVERAGE_SPEED_DIFF']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=12)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
#DEEP LEARNING!
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

bclfr = Sequential()

bclfr.add(Dense(units = 15, kernel_initializer = 'uniform', activation = 'relu', input_dim=17))

bclfr.add(Dense(units = 15, kernel_initializer = 'uniform', activation = 'relu'))

bclfr.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'relu'))

bclfr.add(Dense(units = 7, kernel_initializer = 'uniform', activation = 'relu'))

bclfr.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'softmax'))

bclfr.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])


In [12]:
#Trainning

from tqdm.keras import TqdmCallback

bclfr.fit(X_train,y_train,batch_size=9024, epochs =1000000,verbose=0, callbacks=[TqdmCallback(verbose=0)])

0epoch [00:00, ?epoch/s]

In [13]:
test_data = test_data.drop(['record_date'], axis=1)
test_data = test_data.drop(['city_name'], axis=1)
test_data = test_data.drop(['AVERAGE_CLOUDINESS'], axis=1)
test_data = test_data.drop(['AVERAGE_RAIN'], axis=1)
test_data = test_data.drop(['AVERAGE_PRECIPITATION'], axis=1)
#nan

# céu claro
#ceu limpo

#nuvens dispersas
#algumas nuvens
#ceu pouco nublado
#nuvens quebrados
#nuvens qubradas

#nublado
#tempo nublado

test_data.replace(to_replace =r'^\s*$', 
                 value = 0.3, 
                regex=True,
                 inplace = True)

test_data["AVERAGE_CLOUDINESS"] = training_data["AVERAGE_CLOUDINESS"].fillna("MISSING VALUE")


test_data.replace(to_replace ="MISSING VALUE", 
                 value = 0.555555, 
                  inplace = True)

test_data.replace(to_replace ="céu claro", 
                 value = 0.999999, 
                  inplace = True)

test_data.replace(to_replace ="céu limpo", 
                 value = 0.999999, 
                  inplace = True)

test_data.replace(to_replace ="nuvens dispersas", 
                 value = 0.666666, 
                  inplace = True)


test_data.replace(to_replace ="algumas nuvens", 
                 value = 0.666666, 
                  inplace = True)

test_data.replace(to_replace ="céu pouco nublado", 
                 value = 0.666666, 
                  inplace = True)

test_data.replace(to_replace ="nuvens quebrados", 
                 value = 0.666666, 
                  inplace = True)

test_data.replace(to_replace ="nuvens quebradas", 
                 value = 0.666666, 
                  inplace = True)

test_data.replace(to_replace ="nublado", 
                 value = 0.333333, 
                  inplace = True)

test_data.replace(to_replace ="tempo nublado", 
                 value = 0.333333, 
                  inplace = True)

test_data.replace(to_replace ="NULL", 
                 value = 0.3, 
                  inplace = True)

#Agora temos de tratar da Luminosity

test_data.replace(to_replace ="DARK", 
                 value = 0.333333, 
                  inplace = True)

test_data.replace(to_replace ="LOW_LIGHT", 
                 value = 0.666666, 
                  inplace = True)

test_data.replace(to_replace ="LIGHT", 
                 value = 0.999999, 
                  inplace = True)



test_data.head()

#Normalzie data

test_data['AVERAGE_FREE_FLOW_SPEED'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_FREE_FLOW_SPEED']).reshape(-1,1))
test_data['AVERAGE_TIME_DIFF'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_TIME_DIFF']).reshape(-1,1))
test_data['AVERAGE_FREE_FLOW_TIME'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_FREE_FLOW_TIME']).reshape(-1,1))
test_data['AVERAGE_TEMPERATURE'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_TEMPERATURE']).reshape(-1,1))
test_data['AVERAGE_ATMOSP_PRESSURE'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_ATMOSP_PRESSURE']).reshape(-1,1))
test_data['AVERAGE_HUMIDITY'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_HUMIDITY']).reshape(-1,1))
test_data['AVERAGE_WIND_SPEED'] = MinMaxScaler().fit_transform(np.array(test_data['AVERAGE_WIND_SPEED']).reshape(-1,1))
test_data.head()

AVERAGE_FREE_FLOW_SPEED  AVERAGE_TIME_DIFF  AVERAGE_FREE_FLOW_TIME  \
0                 0.325397           0.000000                0.739655   
1                 0.456349           0.052518                0.494828   
2                 0.591270           0.000000                0.658621   
3                 0.087302           0.222557                0.720690   
4                 0.515873           0.015067                0.644828   

   LUMINOSITY  AVERAGE_TEMPERATURE  AVERAGE_ATMOSP_PRESSURE  AVERAGE_HUMIDITY  \
0    0.333333             0.225806                 0.854167          0.662791   
1    0.333333             0.322581                 0.729167          0.918605   
2    0.333333             0.419355                 0.666667          0.918605   
3    0.999999             0.677419                 0.645833          0.732558   
4    0.333333             0.354839                 0.395833          1.000000   

   AVERAGE_WIND_SPEED  00:00-06:59  07:00-10:59  11:00-13:59  14:00-16:59  \
0            0.076923            0            0            0            0   
1            0.307692            0            0            0            0   
2            0.000000            1            0            0            0   
3            0.307692            0            0            0            0   
4            0.692308            1            0            0            0   

   17:00-18:59  19:00-20:59  21:00-23:59  IsDayOfWeek  AVERAGE_CLOUDINESS  
0            0            0            1            1            0.795883  
1            0            1            0            1            0.999999  
2            0            0            0            1            0.795883  
3            1            0            0            0            0.999999  
4            0            0            0            1            0.795883

In [14]:
pred = bclfr.predict(test_data) 
print(pred)

pred = np.argmax(pred, axis = 1)

df = pd.DataFrame(pred, columns = ['Speed_Diff'])
df_f = df.set_axis(["Speed_Diff"], axis=1)
df_f.index = df_f.index+1

df_f.replace(to_replace = 0, 
                 value = "None", 
                  inplace = True)
df_f.replace(to_replace = 1, 
                 value = "Low", 
                  inplace = True)
df_f.replace(to_replace = 2, 
                 value = "Medium", 
                  inplace = True)
df_f.replace(to_replace = 3, 
                 value = "High", 
                  inplace = True)
df_f.replace(to_replace = 4, 
                 value = "Very_High", 
                  inplace = True)


print(df_f)

df_f.to_csv("submission4_Deep.csv", index_label='RowId')

[[6.1658866e-08 2.3249349e-08 1.2451587e-02 9.8754835e-01 3.5148286e-36]
 [1.1153685e-07 3.4354244e-08 1.1816946e-02 9.8818028e-01 2.5834368e-06]
 [4.5216257e-08 1.8953019e-08 1.2796926e-02 9.8720306e-01 0.0000000e+00]
 ...
 [2.2844310e-08 6.7448749e-09 2.1149530e-03 1.7882952e-01 8.1905556e-01]
 [9.9563181e-01 4.3679411e-03 2.7310085e-07 0.0000000e+00 0.0000000e+00]
 [4.3390699e-12 4.2664920e-11 2.8755674e-02 9.7124434e-01 0.0000000e+00]]
     Speed_Diff
1          High
2          High
3          High
4        Medium
5          High
...         ...
1496       High
1497       High
1498  Very_High
1499       None
1500       High

[1500 rows x 1 columns]


In [15]:
pred = bclfr.predict(X) 
print(pred)

pred = np.argmax(pred, axis = 1)

df = pd.DataFrame(pred, columns = ['Speed_Diff'])
df_f = df.set_axis(["Speed_Diff"], axis=1)
df_f.index = df_f.index+1

df_f.replace(to_replace = 0, 
                 value = "None", 
                  inplace = True)
df_f.replace(to_replace = 1, 
                 value = "Low", 
                  inplace = True)
df_f.replace(to_replace = 2, 
                 value = "Medium", 
                  inplace = True)
df_f.replace(to_replace = 3, 
                 value = "High", 
                  inplace = True)
df_f.replace(to_replace = 4, 
                 value = "Very_High", 
                  inplace = True)


print(df_f)

[[2.7893933e-16 7.3220631e-14 6.5377444e-02 9.3462259e-01 0.0000000e+00]
 [7.9539222e-12 1.4653471e-10 4.2853346e-01 5.7146651e-01 0.0000000e+00]
 [6.0146586e-15 5.5592190e-13 5.0536614e-02 9.4946343e-01 0.0000000e+00]
 ...
 [4.6549862e-09 1.2286073e-01 8.7713927e-01 0.0000000e+00 0.0000000e+00]
 [1.1460028e-12 2.5578714e-03 9.9744213e-01 0.0000000e+00 0.0000000e+00]
 [2.2844310e-08 6.7448749e-09 2.1149530e-03 1.7882952e-01 8.1905556e-01]]
     Speed_Diff
1          High
2          High
3          High
4          High
5        Medium
...         ...
6808       High
6809       High
6810     Medium
6811     Medium
6812  Very_High

[6812 rows x 1 columns]
